debug=true
spring.application.name=backend
spring.application.port=${SERVER_PORT}

# DATASOURCE (Aponta ao Postgre Sql)
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/lapazdb
spring.datasource.username=seu_usuario_do_postgres
spring.datasource.password=sua_senha_do_postgres

#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=sa
#spring.datasource.password=

# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 CLIENT
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.root=INFO
logging.level.com.oficina_dev.backend=DEBUG
logging.level.org.springframework=INFO
logging.level.org.hibernate=WARN

logging.file.path=./logs
logging.file.name=${logging.file.path}/application.log

management.endpoints.web.exposure.include=info,health,metrics,loggers
management.endpoint.health.show-details=when_authorized
management.endpoint.loggers.enabled=true

server.error.include-stacktrace=never
